#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

rm log.blockMesh
# Meshing
runApplication blockMesh
# runApplication surfaceFeatures
# runApplication snappyHexMesh -overwrite
# extrudeMesh
touch flowfield.foam

# Output message
echo Mesh created