#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Clean run time folders
restore0Dir

foamListTimes -rm
rm log*
rm -rf postProcessing

touch case.foam

# Mapping fields
mapFields -sourceRegion air -sourceTime latestTime ../ehd_9kv_2khz_case2

runApplication $(getApplication) 

postProcess -func "mag(U)" -latestTime
postProcess -func singleGraph -latestTime

echo
echo Case ended
